#!/bin/bash
#PBS-l nodes=4:ppn=4
#PBS-l walltime=00:10:00
#PBS-o /home/cpsc435_s13/dkanda/lab3/outpoot.txt
#PBS-j oe
#PBS-N lab3

date

export NPROCS=`wc -l $PBS_NODEFILE |gawk '//{print $1}'`
export MCA_OPTS="--mca btl_tcp_if_include eth0 --mca oob_tcp_if_include eth0 --mca btl_tcp_endpoint_cache 65536 --mca oob_tcp_peer_retries 120 --mca oob_tcp_listen_mode listen_thread --mca btl self,tcp"
export PROGRAM="/home/cpsc435_s13/dkanda/lab3/lab3"
mpirun -np $NPROCS -machinefile $PBS_NODEFILE $MCA_OPTS $PROGRAM

date

exit 0